/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Complains;
import Classes.Product;
import Classes.inquiry;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class AdminResponse extends javax.swing.JFrame {

    /**
     * Creates new form AdminResponse
     */
    public AdminResponse() {
        initComponents();
        fillTable();
        fillTable1();
    }
     public final void fillTable(){          
        try {
            FileInputStream fin = new FileInputStream ("inquiry.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<inquiry> productlist = new ArrayList<>();
            productlist = (ArrayList<inquiry>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel) tblres.getModel();
            Object rowData[] = new Object[4];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).getUsername();
                rowData[1] = productlist.get(i).getEmail();
                rowData[2] = productlist.get(i).getSubject();
                rowData[3] = productlist.get(i).getMessage();
           
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }
     public final void fillTable1(){          
        try {
            FileInputStream fin = new FileInputStream ("complain.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Complains> productlist = new ArrayList<>();
            productlist = (ArrayList<Complains>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel) tblcom.getModel();
            Object rowData[] = new Object[3];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).getUsername();
                rowData[1] = productlist.get(i).getMail();
                rowData[2] = productlist.get(i).getComplain();
               
           
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndashboard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblres = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcom = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndashboard.setBorderPainted(false);
        btndashboard.setContentAreaFilled(false);
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 50));

        tblres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Email", "Subject", "Message"
            }
        ));
        jScrollPane1.setViewportView(tblres);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 800, 160));

        tblcom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer name", "Email", "Complains"
            }
        ));
        jScrollPane2.setViewportView(tblcom);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 800, 190));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/response.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        AdminPage admin = new AdminPage();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminResponse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btndashboard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblcom;
    private javax.swing.JTable tblres;
    // End of variables declaration//GEN-END:variables
}
