/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Product;
import Classes.StoreAdmin;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class AdminAddItem extends javax.swing.JFrame {

    /**
     * Creates new form Additem
     */
    ArrayList<Product> productlist = new ArrayList<>();
    public AdminAddItem() {
        initComponents();
        fillTable();
    }
    public final void fillTable(){          
        try {
            FileInputStream fin = new FileInputStream ("product.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
           
            productlist = (ArrayList<Product>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel) tblproduct.getModel();
            Object rowData[] = new Object[6];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).category;
                rowData[1] = productlist.get(i).productName;
                rowData[2] = productlist.get(i).productId;
                rowData[3] = productlist.get(i).quantity;
                rowData[4] = productlist.get(i).location;
                rowData[5] = productlist.get(i).price;
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndashboard = new javax.swing.JButton();
        btndone = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        txtfoodname = new javax.swing.JTextField();
        txtfoodid = new javax.swing.JTextField();
        txtfoodqunantity = new javax.swing.JTextField();
        txtfoodprice = new javax.swing.JTextField();
        txtfoodlocation = new javax.swing.JTextField();
        txtcat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduct = new javax.swing.JTable();
        background = new javax.swing.JLabel();
        msg = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndashboard.setBorderPainted(false);
        btndashboard.setContentAreaFilled(false);
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 50));

        btndone.setBackground(new java.awt.Color(107, 103, 103));
        btndone.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btndone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.JPG"))); // NOI18N
        btndone.setBorderPainted(false);
        btndone.setOpaque(false);
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });
        getContentPane().add(btndone, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 110, 30));

        lbl1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl1.setText("Location");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        lbl2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl2.setText("Food category");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        lbl3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl3.setText("Food Name");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        lbl4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl4.setText("Food Id");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        lbl5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl5.setText("Price");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        lbl6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl6.setText("Quantity");
        getContentPane().add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        txtfoodname.setOpaque(false);
        getContentPane().add(txtfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 230, -1));

        txtfoodid.setOpaque(false);
        getContentPane().add(txtfoodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 230, -1));

        txtfoodqunantity.setOpaque(false);
        getContentPane().add(txtfoodqunantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 230, -1));

        txtfoodprice.setOpaque(false);
        getContentPane().add(txtfoodprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 230, -1));

        txtfoodlocation.setOpaque(false);
        getContentPane().add(txtfoodlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 230, -1));
        getContentPane().add(txtcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 230, -1));

        tblproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food category", "Name", "Food ID", "Quantity", "Location", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblproduct);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 800, 230));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/additem.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        AdminPage admin = new AdminPage();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndashboardActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        String category = txtcat.getText();
        String name = txtfoodname.getText();
        String id = txtfoodid.getText();
        int quantity = Integer.parseInt(txtfoodqunantity.getText());
        String location = txtfoodlocation.getText();
        double price = Double.parseDouble(txtfoodprice.getText());

        if(name.equalsIgnoreCase("")|| id.equalsIgnoreCase("")|| location.equalsIgnoreCase("")|| category.equalsIgnoreCase("")){
            msg.showMessageDialog(this, "Fill all the blanks", "product add status", 0);
        }else{
            Product p = new Product(id, name, price, quantity, category, location);
            StoreAdmin ad = new StoreAdmin();
            if(ad.addProduct(p)){
                msg.showMessageDialog(this, "succesfully added","Product add status", 1);
            }
        }

    }//GEN-LAST:event_btndoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btndone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JOptionPane msg;
    private javax.swing.JTable tblproduct;
    private javax.swing.JTextField txtcat;
    private javax.swing.JTextField txtfoodid;
    private javax.swing.JTextField txtfoodlocation;
    private javax.swing.JTextField txtfoodname;
    private javax.swing.JTextField txtfoodprice;
    private javax.swing.JTextField txtfoodqunantity;
    // End of variables declaration//GEN-END:variables
}
