/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Customer;
import Classes.Order;
import Classes.OrderItem;
import Classes.Product;
import Classes.StoreAdmin;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class AdminPhoneOrder extends javax.swing.JFrame {

    /**
     * Creates new form AdminPhoneOrder
     */
    public AdminPhoneOrder() {
        initComponents();
        fillTable();
        Table1();
        
    }
     public final void fillTable(){          
        try {
            FileInputStream fin = new FileInputStream ("order.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Order> productlist = new ArrayList<>();
            productlist = (ArrayList<Order>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblorder.getModel();
            Object rowData[] = new Object[6];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).getOrderid();
                rowData[1] = productlist.get(i).getDate();
                rowData[2] = productlist.get(i).getTotal();
                rowData[3] = productlist.get(i).getAddress();
                rowData[4] = productlist.get(i).getTelephone();
                rowData[5] = productlist.get(i).getUsername();
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }
     
          public final void Table1(){          
        try {
            FileInputStream fin = new FileInputStream ("orderitem.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<OrderItem> productlist1 = new ArrayList<>();
            productlist1 = (ArrayList<OrderItem>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblitem.getModel();
            Object rowData[] = new Object[3];
            for(int i = 0; i < productlist1.size(); i++){
                rowData[0] = productlist1.get(i).getOrderNo();
                rowData[1] = productlist1.get(i).getItem();
                rowData[2] = productlist1.get(i).getQuantity();
                
                
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtoid = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        txtquan = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtcus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndashboard.setBorderPainted(false);
        btndashboard.setContentAreaFilled(false);
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 50));

        jLabel1.setText("Order Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel2.setText("Product ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel5.setText("Telephone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        jLabel6.setText("Cutomer name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        txtoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoidActionPerformed(evt);
            }
        });
        getContentPane().add(txtoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 220, -1));

        txtpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpidActionPerformed(evt);
            }
        });
        getContentPane().add(txtpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 220, -1));
        getContentPane().add(txtquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, -1));

        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        getContentPane().add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 220, -1));
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 220, -1));
        getContentPane().add(txtcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 220, -1));

        jButton1.setText("Add Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 90, -1));

        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Date", "Total", "Address", "Telephone", "Customer"
            }
        ));
        jScrollPane1.setViewportView(tblorder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 650, 160));

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Product Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(tblitem);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 650, 160));

        jLabel7.setText("Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 220, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phoneorders.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        AdminPage admin = new AdminPage();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndashboardActionPerformed

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddActionPerformed

    private void txtoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoidActionPerformed

    private void txtpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uname = txtcus.getText();
       String pid = txtpid.getText();
       int quan = Integer.parseInt(txtquan.getText());
       double total = 0.0;
       String oid = txtoid.getText();
       String tel = txttel.getText();
       String add = txtadd.getText();
       String date = txtdate.getText();
       
        try {
            FileInputStream fin = new FileInputStream ("product.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Product> productlist = new ArrayList<>();
            productlist = (ArrayList<Product>) ois.readObject();
            for(int i = 0; i < productlist.size(); i++){
                   if(pid.equals(productlist.get(i).productId)){
                       double price = productlist.get(i).price;
                       total = price * quan;
                       Order o = new Order(oid, date, total, tel, add,uname);
                       o.createOrderItem(oid, productlist.get(i).productName, quan);
                       StoreAdmin c = new StoreAdmin();
                       if(c.addPhoneOrder(o)){
                           JOptionPane.showMessageDialog(this, "succesfully added", "order status", 1);
                       }
                       
                   }
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPhoneOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPhoneOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPhoneOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPhoneOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPhoneOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblitem;
    private javax.swing.JTable tblorder;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtcus;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtquan;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    
}
