/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Offer;
import Classes.StoreAdmin;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class AdminAddOffer extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddOffer
     */
    public AdminAddOffer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndashboard = new javax.swing.JButton();
        cmbveg = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtoff = new javax.swing.JTextArea();
        btndone = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndashboard.setBorderPainted(false);
        btndashboard.setContentAreaFilled(false);
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 50));

        cmbveg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetable", "Meat", "Milk", "Fruit", "Bakery", "Bevarages" }));
        getContentPane().add(cmbveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 230, -1));

        txtoff.setColumns(20);
        txtoff.setRows(5);
        txtoff.setOpaque(false);
        jScrollPane1.setViewportView(txtoff);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 500, -1));

        btndone.setBackground(new java.awt.Color(107, 103, 103));
        btndone.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btndone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.JPG"))); // NOI18N
        btndone.setBorderPainted(false);
        btndone.setOpaque(false);
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });
        getContentPane().add(btndone, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 110, 30));

        lbl2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl2.setText("Offer Description");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        lbl3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl3.setText("Food category");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addoffer.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        AdminPage admin = new AdminPage();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndashboardActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
       String cat = (String) cmbveg.getSelectedItem();
       String offe = txtoff.getText();
       
       Offer of = new Offer(cat, offe);
        StoreAdmin ad = new StoreAdmin();
        if(ad.addOffer(of)){
            JOptionPane.showMessageDialog(this,"Succesfully added", "offer status", 1);
        }
    }//GEN-LAST:event_btndoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddOffer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btndone;
    private javax.swing.JComboBox<String> cmbveg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JTextArea txtoff;
    // End of variables declaration//GEN-END:variables
}
