/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnadditem = new javax.swing.JButton();
        btnaddoffer = new javax.swing.JButton();
        btnphoneorder = new javax.swing.JButton();
        btnreponse = new javax.swing.JButton();
        btngenerate = new javax.swing.JButton();
        btndeliveryshedule = new javax.swing.JButton();
        btncollectionshedule = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadditem.setBorderPainted(false);
        btnadditem.setContentAreaFilled(false);
        btnadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadditemActionPerformed(evt);
            }
        });
        getContentPane().add(btnadditem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

        btnaddoffer.setBorderPainted(false);
        btnaddoffer.setContentAreaFilled(false);
        btnaddoffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddofferActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddoffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 60));

        btnphoneorder.setBorderPainted(false);
        btnphoneorder.setContentAreaFilled(false);
        btnphoneorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphoneorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnphoneorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 60));

        btnreponse.setBorderPainted(false);
        btnreponse.setContentAreaFilled(false);
        btnreponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreponseActionPerformed(evt);
            }
        });
        getContentPane().add(btnreponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 60));

        btngenerate.setBorderPainted(false);
        btngenerate.setContentAreaFilled(false);
        btngenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerateActionPerformed(evt);
            }
        });
        getContentPane().add(btngenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 240, 60));

        btndeliveryshedule.setBorderPainted(false);
        btndeliveryshedule.setContentAreaFilled(false);
        btndeliveryshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeliverysheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btndeliveryshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 240, 60));

        btncollectionshedule.setBorderPainted(false);
        btncollectionshedule.setContentAreaFilled(false);
        btncollectionshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncollectionsheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btncollectionshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 60));

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 60, 10));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadditemActionPerformed
        AdminAddItem add = new AdminAddItem();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadditemActionPerformed

    private void btnaddofferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddofferActionPerformed
        AdminAddOffer offer = new AdminAddOffer();
        offer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddofferActionPerformed

    private void btnphoneorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphoneorderActionPerformed
        AdminPhoneOrder order = new AdminPhoneOrder();
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnphoneorderActionPerformed

    private void btnreponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreponseActionPerformed
        AdminResponse adminresponse = new AdminResponse();
        adminresponse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnreponseActionPerformed

    private void btngenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateActionPerformed
        AdminGenerate generate = new AdminGenerate();
        generate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngenerateActionPerformed

    private void btndeliverysheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeliverysheduleActionPerformed
        AdminDeliverySchedule delivery = new AdminDeliverySchedule();
        delivery.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndeliverysheduleActionPerformed

    private void btncollectionsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncollectionsheduleActionPerformed
        AdminCollectionSchedule collection = new AdminCollectionSchedule();
        collection.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncollectionsheduleActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnadditem;
    private javax.swing.JButton btnaddoffer;
    private javax.swing.JButton btncollectionshedule;
    private javax.swing.JButton btndeliveryshedule;
    private javax.swing.JButton btngenerate;
    private javax.swing.JButton btnphoneorder;
    private javax.swing.JButton btnreponse;
    private javax.swing.JButton btnsignout;
    // End of variables declaration//GEN-END:variables
}
