/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Complains;
import Classes.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class CustomerComplains extends javax.swing.JFrame {

    /**
     * Creates new form CustomerComplains
     */
    String username;
    public CustomerComplains() {
        initComponents();
    }
     public CustomerComplains(String username) {
        initComponents();
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txtcomplain = new javax.swing.JTextField();
        btndone = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnorders = new javax.swing.JButton();
        btnmycart = new javax.swing.JButton();
        btncategory = new javax.swing.JButton();
        btnlodecomplain = new javax.swing.JButton();
        btninqiure = new javax.swing.JButton();
        btnaboutus = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        btnback1 = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnhome1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl3.setForeground(java.awt.SystemColor.controlShadow);
        lbl3.setText("Complain Description");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 160, 30));

        lbl4.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        lbl4.setForeground(new java.awt.Color(102, 102, 102));
        lbl4.setText("CUSTOMER COMPLAINS");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, 30));

        txtcomplain.setBackground(java.awt.SystemColor.controlHighlight);
        txtcomplain.setOpaque(false);
        getContentPane().add(txtcomplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 230, -1));

        btndone.setBackground(new java.awt.Color(107, 103, 103));
        btndone.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btndone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.JPG"))); // NOI18N
        btndone.setBorderPainted(false);
        btndone.setOpaque(false);
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });
        getContentPane().add(btndone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 100, 30));

        btnback.setBackground(java.awt.SystemColor.controlHighlight);
        btnback.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 700, 70, 30));

        btnorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderbutton.JPG"))); // NOI18N
        btnorders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnorders.setContentAreaFilled(false);
        btnorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersActionPerformed(evt);
            }
        });
        getContentPane().add(btnorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, -1));

        btnmycart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartbutton.JPG"))); // NOI18N
        btnmycart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnmycart.setContentAreaFilled(false);
        btnmycart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycartActionPerformed(evt);
            }
        });
        getContentPane().add(btnmycart, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 150, -1));

        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/catesmall.jpg"))); // NOI18N
        btncategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 10));

        btnlodecomplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locsmall.jpg"))); // NOI18N
        btnlodecomplain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlodecomplain.setContentAreaFilled(false);
        btnlodecomplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodecomplainActionPerformed(evt);
            }
        });
        getContentPane().add(btnlodecomplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 10));

        btninqiure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inqui.jpg"))); // NOI18N
        btninqiure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btninqiure.setContentAreaFilled(false);
        btninqiure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninqiureActionPerformed(evt);
            }
        });
        getContentPane().add(btninqiure, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 70, 10));

        btnaboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutus.jpg"))); // NOI18N
        btnaboutus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnaboutus.setContentAreaFilled(false);
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });
        getContentPane().add(btnaboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 70, 10));

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        jLabel1.setForeground(java.awt.SystemColor.controlShadow);
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 454, 150, 30));

        txtmail.setBackground(java.awt.SystemColor.controlHighlight);
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 230, -1));

        btnback1.setBackground(java.awt.SystemColor.controlHighlight);
        btnback1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        btnback1.setText("Back");
        btnback1.setBorderPainted(false);
        btnback1.setContentAreaFilled(false);
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 700, 70, 30));

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home3.JPG"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        btnhome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home3.JPG"))); // NOI18N
        btnhome1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnhome1.setContentAreaFilled(false);
        btnhome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        background.setBackground(java.awt.SystemColor.controlHighlight);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.JPG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersActionPerformed
        Orders order = new Orders();
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnordersActionPerformed

    private void btnmycartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycartActionPerformed
        CustomerCart cart = new CustomerCart();
        cart.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnmycartActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        CategorySearch cate = new CategorySearch();
        cate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnlodecomplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodecomplainActionPerformed
        CustomerComplains com = new CustomerComplains();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlodecomplainActionPerformed

    private void btninqiureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninqiureActionPerformed
        CustomerInquire inquire = new CustomerInquire();
        inquire.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninqiureActionPerformed

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
        CustomerAboutUs aboutus = new CustomerAboutUs();
        aboutus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
       String complain = txtcomplain.getText();
       String mail = txtmail.getText();
        Complains ci = new Complains(this.username, complain,mail);
        Customer cus = new Customer();
        if(cus.complainsAndInquires(ci)){
            JOptionPane.showMessageDialog(this, "Succesfully added", "complain status", 1);
        }
    }//GEN-LAST:event_btndoneActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnhome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome1ActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerComplains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btndone;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnhome1;
    private javax.swing.JButton btninqiure;
    private javax.swing.JButton btnlodecomplain;
    private javax.swing.JButton btnmycart;
    private javax.swing.JButton btnorders;
    private javax.swing.JButton btnsignout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField txtcomplain;
    private javax.swing.JTextField txtmail;
    // End of variables declaration//GEN-END:variables
}
