/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Customer;
import Classes.Order;
import Classes.Product;
import Classes.ShoppingCart;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class CustomerPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPage
     */
    private String username;
    private String product;
    public CustomerPage() {
        initComponents();
        fillTable();
    }
    public CustomerPage(String username){
         initComponents();
        fillTable();
        this.username = username;
    }
    public CustomerPage(String username,String prod){
           initComponents();
        fillTable();
        this.username = username;
        this.product = prod;
    }
        public final void fillTable(){          
        try {
            FileInputStream fin = new FileInputStream ("product.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Product> productlist = new ArrayList<>();
            productlist = (ArrayList<Product>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel) tblproduct.getModel();
            Object rowData[] = new Object[6];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).category;
                rowData[1] = productlist.get(i).productName;
                rowData[2] = productlist.get(i).productId;
                rowData[3] = productlist.get(i).quantity;
                rowData[4] = productlist.get(i).location;
                rowData[5] = productlist.get(i).price;
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgbox = new javax.swing.JOptionPane();
        btnorders = new javax.swing.JButton();
        btnmycart = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        btnaboutus = new javax.swing.JButton();
        btninqiure = new javax.swing.JButton();
        btnlodecomplain = new javax.swing.JButton();
        btncategory = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtquan = new javax.swing.JTextField();
        btncart = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtord = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtvou = new javax.swing.JTextField();
        btnvoucher = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderbutton.JPG"))); // NOI18N
        btnorders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnorders.setContentAreaFilled(false);
        btnorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersActionPerformed(evt);
            }
        });
        getContentPane().add(btnorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, -1));

        btnmycart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartbutton.JPG"))); // NOI18N
        btnmycart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnmycart.setContentAreaFilled(false);
        btnmycart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycartActionPerformed(evt);
            }
        });
        getContentPane().add(btnmycart, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 150, -1));

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        btnaboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutus.jpg"))); // NOI18N
        btnaboutus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnaboutus.setContentAreaFilled(false);
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });
        getContentPane().add(btnaboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 70, 10));

        btninqiure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inqui.jpg"))); // NOI18N
        btninqiure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btninqiure.setContentAreaFilled(false);
        btninqiure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninqiureActionPerformed(evt);
            }
        });
        getContentPane().add(btninqiure, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 70, 10));

        btnlodecomplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locsmall.jpg"))); // NOI18N
        btnlodecomplain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlodecomplain.setContentAreaFilled(false);
        btnlodecomplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodecomplainActionPerformed(evt);
            }
        });
        getContentPane().add(btnlodecomplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 10));

        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/catesmall.jpg"))); // NOI18N
        btncategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 10));

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home3.JPG"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);

        tblproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Name", "ID", "Quantity", "Location", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblproduct);

        jLabel1.setText("Product ID");

        jLabel2.setText("Quantity");

        txtpid.setBackground(java.awt.SystemColor.controlHighlight);

        txtquan.setBackground(java.awt.SystemColor.controlHighlight);
        txtquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquanActionPerformed(evt);
            }
        });

        btncart.setBackground(java.awt.SystemColor.inactiveCaption);
        btncart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addtocart.JPG"))); // NOI18N
        btncart.setBorderPainted(false);
        btncart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncartActionPerformed(evt);
            }
        });

        btnorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/makeorder.JPG"))); // NOI18N
        btnorder.setBorderPainted(false);
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        jLabel3.setText("Order ID");

        txtord.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel4.setText("Telephone Number");

        txtnum.setBackground(java.awt.SystemColor.controlHighlight);

        txtaddress.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel5.setText("Delivary addrres");

        jLabel6.setText("Date");

        txtdate.setBackground(java.awt.SystemColor.controlHighlight);
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        jLabel7.setText("Voucher id");

        txtvou.setBackground(java.awt.SystemColor.controlHighlight);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtord, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtquan, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtpid, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtvou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtaddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(143, 143, 143))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncart, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnorder, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtvou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btnorder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btncart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(129, 129, 129))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1200, 490));

        btnvoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voucher.JPG"))); // NOI18N
        btnvoucher.setBorderPainted(false);
        btnvoucher.setContentAreaFilled(false);
        btnvoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoucherActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, 70, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CustomerPAgefINAL2.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersActionPerformed
            Orders order = new Orders(this.username);
            order.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnordersActionPerformed

    private void btnmycartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycartActionPerformed
            CustomerCart cart = new CustomerCart(this.username);
            cart.setVisible(true);
            this.dispose();
           
    }//GEN-LAST:event_btnmycartActionPerformed

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
            CustomerAboutUs aboutus = new CustomerAboutUs();
            aboutus.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        CategorySearch cate = new CategorySearch();
        cate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnlodecomplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodecomplainActionPerformed
        CustomerComplains com = new CustomerComplains(this.username);
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlodecomplainActionPerformed

    private void btninqiureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninqiureActionPerformed
        CustomerInquire inquire = new CustomerInquire(this.username);
        inquire.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninqiureActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void txtquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquanActionPerformed

    private void btncartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncartActionPerformed
        String qu = txtquan.getText();
        String id = txtord.getText();
        String nu = txtnum.getText();
        String ad = txtaddress.getText();
        String dat = txtdate.getText();
        
        
        String uname = this.username;
        String pid = txtpid.getText();
        ShoppingCart s = new ShoppingCart(uname, pid);
        Customer c1 = new Customer();
        
        
        if(pid.equals("")&& qu.equals("") && id.equals("") && nu.equals("") && ad.equals("") && dat.equals("")){
            JOptionPane.showMessageDialog(this, "Please fill the Blacks","Add to cart status", 1);
        }
        else{
             c1.addtoCart(s);
            JOptionPane.showMessageDialog(this, "Succesfully Added","Add to cart status", 1);
        }
       
    }//GEN-LAST:event_btncartActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
       String uname = this.username;
       String pid = txtpid.getText();
       int quan = Integer.parseInt(txtquan.getText());
       double total = 0.0;
       String oid = txtord.getText();
       String tel = txtnum.getText();
       String add = txtaddress.getText();
       String date = txtdate.getText();
       String user = this.username;
       String voucher = null;
          voucher= txtvou.getText();
       Order b = new Order();
       double amount = b.radeemAmount(voucher);
        try {
       
         
            FileInputStream fin = new FileInputStream ("product.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Product> productlist = new ArrayList<>();
            productlist = (ArrayList<Product>) ois.readObject();
            for(int i = 0; i < productlist.size(); i++){
                   if(pid.equals(productlist.get(i).productId)){
                       double price = productlist.get(i).price;
                       total = (price * quan) - amount;
                       Order o = new Order(oid, date, total, tel, add,user);
                       o.createOrderItem(oid, productlist.get(i).productName, quan);
                         
                       
                       Customer c = new Customer();
                       if(c.addOrder(o)){
                           JOptionPane.showMessageDialog(this, "succesfully added", "order status", 1);
                       }
                       
                   }
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }//GEN-LAST:event_btnorderActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void btnvoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoucherActionPerformed
       CustomerVoucher vc = new CustomerVoucher();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoucherActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btncart;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btninqiure;
    private javax.swing.JButton btnlodecomplain;
    private javax.swing.JButton btnmycart;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnorders;
    private javax.swing.JButton btnsignout;
    private javax.swing.JButton btnvoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane msgbox;
    private javax.swing.JTable tblproduct;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtord;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtquan;
    private javax.swing.JTextField txtvou;
    // End of variables declaration//GEN-END:variables
}
