/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Customer;
import Classes.Product;
import Classes.ShoppingCart;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class CustomerCart extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCart
     */
    String username;
    public CustomerCart() {
        initComponents();
        filltable();
    }
    public CustomerCart(String username){
        initComponents();
        this.username = username;
        filltable();
    }
    public final void filltable(){
        try {
            FileInputStream fin = new FileInputStream ("cart.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<ShoppingCart> cartlist = new ArrayList<>();
            cartlist = (ArrayList<ShoppingCart>) ois.readObject();
            
            FileInputStream fine = new FileInputStream ("product.txt");
            ObjectInputStream oise = new ObjectInputStream(fine);
            ArrayList<Product> productlist = new ArrayList<>();
            productlist = (ArrayList<Product>) oise.readObject();
            
            DefaultTableModel model = (DefaultTableModel) tblcart.getModel();
            Object rowData[] = new Object[3];
            for(int i = 0; i < cartlist.size(); i++){
                if(username.equals(cartlist.get(i).getUserid())){
                    String pid = cartlist.get(i).getPid();
                    for(int a = 0; a < productlist.size(); a++){
                        if(pid.equals(productlist.get(a).productId)){
                            rowData[0] = productlist.get(a).productId;
                            rowData[1] = productlist.get(a).productName;
                            rowData[2] = productlist.get(a).price;
                            model.addRow(rowData);
                        }
                    }
                }
          
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtitemno = new javax.swing.JTextField();
        btnlodecomplain = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        itemno = new javax.swing.JLabel();
        btnbuynow = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnorders = new javax.swing.JButton();
        btnmycart = new javax.swing.JButton();
        btncategory = new javax.swing.JButton();
        btninqiure = new javax.swing.JButton();
        btnaboutus = new javax.swing.JButton();
        btnsignout1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcart = new javax.swing.JTable();
        btnhome = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtitemno.setBackground(java.awt.SystemColor.controlHighlight);
        txtitemno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtitemno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 280, -1));

        btnlodecomplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locsmall.jpg"))); // NOI18N
        btnlodecomplain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlodecomplain.setContentAreaFilled(false);
        btnlodecomplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodecomplainActionPerformed(evt);
            }
        });
        getContentPane().add(btnlodecomplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 10));

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        lbl1.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        lbl1.setForeground(new java.awt.Color(102, 102, 102));
        lbl1.setText("YOUR SHOPPING CART");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, 30));

        itemno.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        itemno.setText("Item No:");
        getContentPane().add(itemno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 70, -1));

        btnbuynow.setBackground(java.awt.SystemColor.controlHighlight);
        btnbuynow.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        btnbuynow.setText("PROCEED TO CHECKOUT");
        btnbuynow.setBorderPainted(false);
        btnbuynow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuynowActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuynow, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 180, 40));

        btnremove.setBackground(new java.awt.Color(160, 71, 71));
        btnremove.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        btnremove.setText("REMOVE");
        btnremove.setBorderPainted(false);
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 110, 40));

        btnback.setBackground(java.awt.SystemColor.controlHighlight);
        btnback.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 700, 70, -1));

        btnorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderbutton.JPG"))); // NOI18N
        btnorders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnorders.setContentAreaFilled(false);
        btnorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersActionPerformed(evt);
            }
        });
        getContentPane().add(btnorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, -1));

        btnmycart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartbutton.JPG"))); // NOI18N
        btnmycart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnmycart.setContentAreaFilled(false);
        btnmycart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycartActionPerformed(evt);
            }
        });
        getContentPane().add(btnmycart, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 150, -1));

        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/catesmall.jpg"))); // NOI18N
        btncategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 10));

        btninqiure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inqui.jpg"))); // NOI18N
        btninqiure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btninqiure.setContentAreaFilled(false);
        btninqiure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninqiureActionPerformed(evt);
            }
        });
        getContentPane().add(btninqiure, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 70, 10));

        btnaboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutus.jpg"))); // NOI18N
        btnaboutus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnaboutus.setContentAreaFilled(false);
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });
        getContentPane().add(btnaboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 70, 10));

        btnsignout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout1.setContentAreaFilled(false);
        btnsignout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignout1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        tblcart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblcart);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 630, 210));

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home3.JPG"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.JPG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtitemnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemnoActionPerformed

    private void btnbuynowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuynowActionPerformed
        String id = txtitemno.getText();
        CustomerPage cus = new CustomerPage(this.username,id);
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbuynowActionPerformed

    private void btnordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersActionPerformed
        Orders order = new Orders(this.username);
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnordersActionPerformed

    private void btnmycartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycartActionPerformed
        CustomerCart cart = new CustomerCart();
        cart.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnmycartActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        CategorySearch cate = new CategorySearch();
        cate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btninqiureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninqiureActionPerformed
        CustomerInquire inquire = new CustomerInquire();
        inquire.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninqiureActionPerformed

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
        CustomerAboutUs aboutus = new CustomerAboutUs();
        aboutus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void btnlodecomplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodecomplainActionPerformed
        CustomerComplains com = new CustomerComplains();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlodecomplainActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void btnsignout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignout1ActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignout1ActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        String id = txtitemno.getText();
         try {       
            FileInputStream fin = new FileInputStream ("cart.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<ShoppingCart> cartlist = new ArrayList<>();
            cartlist =  (ArrayList<ShoppingCart>) ois.readObject();
            
            
            fin.close();
            for(int i = 0; i < cartlist.size() ; i++){
                if(id.equals(cartlist.get(i).getPid()) && username.equals(cartlist.get(i).getUserid())){
                    ShoppingCart ob = cartlist.get(i);
                    cartlist.remove(ob);
                    JOptionPane.showMessageDialog(this, "succesfully removed", "Cart status", 1);
                }else{
                    JOptionPane.showMessageDialog(this, "Please enter a valid id", "cart status", 0);
                }
            }
            FileOutputStream fos = new FileOutputStream("cart.txt");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(cartlist);
                oos.close();
        } catch (FileNotFoundException ex) {
        
        } catch (IOException | ClassNotFoundException ex) {
           
        } 
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbuynow;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btninqiure;
    private javax.swing.JButton btnlodecomplain;
    private javax.swing.JButton btnmycart;
    private javax.swing.JButton btnorders;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsignout;
    private javax.swing.JButton btnsignout1;
    private javax.swing.JLabel itemno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTable tblcart;
    private javax.swing.JTextField txtitemno;
    // End of variables declaration//GEN-END:variables
}
