/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Customer;
import Classes.inquiry;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class CustomerInquire extends javax.swing.JFrame {

    /**
     * Creates new form CustomerInquire
     */
    String username;
    public CustomerInquire() {
        initComponents();
    }
    public CustomerInquire(String username) {
        initComponents();
        this.username = username;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        btndone = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        txtinquiremessage = new javax.swing.JTextField();
        txtinquiresubject = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btncategory = new javax.swing.JButton();
        btnorders = new javax.swing.JButton();
        btnmycart = new javax.swing.JButton();
        btnlodecomplain = new javax.swing.JButton();
        btninqiure = new javax.swing.JButton();
        btnaboutus = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl2.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        lbl2.setForeground(new java.awt.Color(102, 102, 102));
        lbl2.setText("CUSTOMER INQUIRES");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 340, 30));

        lbl3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(51, 51, 51));
        lbl3.setText("Message");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 160, 30));

        lbl4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(51, 51, 51));
        lbl4.setText("Email");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 80, 30));

        lbl5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbl5.setForeground(new java.awt.Color(51, 51, 51));
        lbl5.setText("Subject");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 160, 30));

        btndone.setBackground(new java.awt.Color(107, 103, 103));
        btndone.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btndone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.JPG"))); // NOI18N
        btndone.setBorderPainted(false);
        btndone.setOpaque(false);
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });
        getContentPane().add(btndone, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 100, 30));

        btnback.setBackground(java.awt.SystemColor.controlHighlight);
        btnback.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 700, 70, 30));

        txtinquiremessage.setBackground(java.awt.SystemColor.controlHighlight);
        txtinquiremessage.setOpaque(false);
        getContentPane().add(txtinquiremessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 270, 60));

        txtinquiresubject.setBackground(java.awt.SystemColor.controlHighlight);
        txtinquiresubject.setOpaque(false);
        txtinquiresubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinquiresubjectActionPerformed(evt);
            }
        });
        getContentPane().add(txtinquiresubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 270, -1));

        txtemail.setBackground(java.awt.SystemColor.controlHighlight);
        txtemail.setOpaque(false);
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 270, -1));

        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/catesmall.jpg"))); // NOI18N
        btncategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 10));

        btnorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderbutton.JPG"))); // NOI18N
        btnorders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnorders.setContentAreaFilled(false);
        btnorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersActionPerformed(evt);
            }
        });
        getContentPane().add(btnorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, -1));

        btnmycart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartbutton.JPG"))); // NOI18N
        btnmycart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnmycart.setContentAreaFilled(false);
        btnmycart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycartActionPerformed(evt);
            }
        });
        getContentPane().add(btnmycart, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 150, -1));

        btnlodecomplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locsmall.jpg"))); // NOI18N
        btnlodecomplain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlodecomplain.setContentAreaFilled(false);
        btnlodecomplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodecomplainActionPerformed(evt);
            }
        });
        getContentPane().add(btnlodecomplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 10));

        btninqiure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inqui.jpg"))); // NOI18N
        btninqiure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btninqiure.setContentAreaFilled(false);
        btninqiure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninqiureActionPerformed(evt);
            }
        });
        getContentPane().add(btninqiure, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 70, 10));

        btnaboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutus.jpg"))); // NOI18N
        btnaboutus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnaboutus.setContentAreaFilled(false);
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });
        getContentPane().add(btnaboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 70, 10));

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home3.JPG"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.JPG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinquiresubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinquiresubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinquiresubjectActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersActionPerformed
        Orders order = new Orders();
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnordersActionPerformed

    private void btnmycartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycartActionPerformed
        CustomerCart cart = new CustomerCart();
        cart.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnmycartActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        CategorySearch cate = new CategorySearch();
        cate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnlodecomplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodecomplainActionPerformed
        CustomerComplains com = new CustomerComplains();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlodecomplainActionPerformed

    private void btninqiureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninqiureActionPerformed
        CustomerInquire inquire = new CustomerInquire();
        inquire.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninqiureActionPerformed

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
        CustomerAboutUs aboutus = new CustomerAboutUs();
        aboutus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        String user = this.username;
        String mail = txtemail.getText();
        String sub = txtinquiresubject.getText();
        String msg = txtinquiremessage.getText();
        inquiry in = new inquiry(username, mail, sub, msg);
        Customer cus = new Customer();
        if(cus.inquire(in)){
            JOptionPane.showMessageDialog(this, "succesfully added", "enquire status", 1);
        }
    }//GEN-LAST:event_btndoneActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInquire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btndone;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btninqiure;
    private javax.swing.JButton btnlodecomplain;
    private javax.swing.JButton btnmycart;
    private javax.swing.JButton btnorders;
    private javax.swing.JButton btnsignout;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtinquiremessage;
    private javax.swing.JTextField txtinquiresubject;
    // End of variables declaration//GEN-END:variables
}
