/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.DeliverySchedule;
import Classes.Order;
import Classes.OrderItem;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class DeliveryOfficer extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryOfficer
     */
    public DeliveryOfficer() {
        initComponents();
        fillTable();
        Table1();
        fillTable1();
    }
     public final void fillTable1(){          
        try {
            FileInputStream fin = new FileInputStream ("delivarySchedule.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<DeliverySchedule> productlist = new ArrayList<>();
            productlist = (ArrayList<DeliverySchedule>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblDelivery.getModel();
            Object rowData[] = new Object[3];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).getDeliveryId();
                rowData[1] = productlist.get(i).getDeliveryDate();
                rowData[2] = productlist.get(i).getOrderid();
                
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }
    
    public final void fillTable(){          
        try {
            FileInputStream fin = new FileInputStream ("order.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Order> productlist = new ArrayList<>();
            productlist = (ArrayList<Order>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblorder.getModel();
            Object rowData[] = new Object[6];
            for(int i = 0; i < productlist.size(); i++){
                rowData[0] = productlist.get(i).getOrderid();
                rowData[1] = productlist.get(i).getDate();
                rowData[2] = productlist.get(i).getTotal();
                rowData[3] = productlist.get(i).getAddress();
                rowData[4] = productlist.get(i).getTelephone();
                rowData[5] = productlist.get(i).getUsername();
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }
     
          public final void Table1(){          
        try {
            FileInputStream fin = new FileInputStream ("orderitem.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<OrderItem> productlist1 = new ArrayList<>();
            productlist1 = (ArrayList<OrderItem>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblitem.getModel();
            Object rowData[] = new Object[3];
            for(int i = 0; i < productlist1.size(); i++){
                rowData[0] = productlist1.get(i).getOrderNo();
                rowData[1] = productlist1.get(i).getItem();
                rowData[2] = productlist1.get(i).getQuantity();
                
                
                model.addRow(rowData);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsignout = new javax.swing.JButton();
        collectionshedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDelivery = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        collectionshedule.setBorderPainted(false);
        collectionshedule.setContentAreaFilled(false);
        collectionshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsheduleActionPerformed(evt);
            }
        });
        getContentPane().add(collectionshedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 190, 40));

        tblDelivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delivery ID", "Delivery date", "Order Number"
            }
        ));
        jScrollPane1.setViewportView(tblDelivery);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 450, 150));

        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Date", "Total", "Address", "Telephone", "Customer"
            }
        ));
        jScrollPane2.setViewportView(tblorder);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 980, 160));

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Product Name", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(tblitem);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 480, 150));

        background.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/collection.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void collectionsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsheduleActionPerformed
        CollectionOfficer collection = new CollectionOfficer();
        collection.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_collectionsheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryOfficer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnsignout;
    private javax.swing.JButton collectionshedule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDelivery;
    private javax.swing.JTable tblitem;
    private javax.swing.JTable tblorder;
    // End of variables declaration//GEN-END:variables
}
