/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Customer;
import Classes.DeliveryPerson;
import Classes.StoreAdmin;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class Loginframe extends javax.swing.JFrame {

    /**
     * Creates new form Loginframe
     */
    public Loginframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgbox = new javax.swing.JOptionPane();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnsignpu = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setBackground(new java.awt.Color(102, 102, 102));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtusername.setDoubleBuffered(true);
        txtusername.setDragEnabled(true);
        txtusername.setFocusCycleRoot(true);
        txtusername.setOpaque(false);
        txtusername.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 250, 20));

        txtpassword.setBackground(new java.awt.Color(102, 102, 102));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 250, 20));

        btnlogin.setBackground(new java.awt.Color(102, 102, 102));
        btnlogin.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login2.JPG"))); // NOI18N
        btnlogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlogin.setBorderPainted(false);
        btnlogin.setContentAreaFilled(false);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 120, 30));

        btnsignpu.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnsignpu.setForeground(new java.awt.Color(204, 204, 0));
        btnsignpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Signup.JPG"))); // NOI18N
        btnsignpu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignpu.setContentAreaFilled(false);
        btnsignpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignpuActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 120, 30));

        background.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Loginpage.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed

    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        Customer cust = new Customer();
        StoreAdmin sa = new StoreAdmin();
        DeliveryPerson dp = new DeliveryPerson();
        if(username.equals("")&& password.equals("")){
             msgbox.showMessageDialog(this, "Please fill the blanks", "Login status", 0);
        }
        else if(cust.login(username, password)){
            CustomerPage cus = new CustomerPage(username);
            cus.setVisible(true);
            this.dispose();
       }
       else if(sa.login(username, password)){
            AdminPage ad = new AdminPage();
            ad.setVisible(true);
            this.dispose();
       }
       else if(dp.login(username, password)){
            DeliveryOfficer deli = new DeliveryOfficer();
            deli.setVisible(true);
            this.dispose();
       }else{
            msgbox.showMessageDialog(this, "incorrect Login", "Login status", 0);
       }
        
       
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnsignpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignpuActionPerformed
        SignUp signup = new SignUp();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignpuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignpu;
    private javax.swing.JOptionPane msgbox;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
