/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Order;
import Classes.OrderItem;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanushan Sasith Lakshan
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    String username;
    ArrayList<String> orderNumber = new ArrayList<>();
    public Orders() {
        initComponents();
    }
     public Orders(String username) {
        initComponents();
        this.username = username;
        fillTable();
        Table1();
    }
         public final void fillTable(){          
        try {
            FileInputStream fin = new FileInputStream ("order.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<Order> productlist = new ArrayList<>();
            productlist = (ArrayList<Order>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblorder.getModel();
            Object rowData[] = new Object[6];
            for(int i = 0; i < productlist.size(); i++){
                if(this.username.equals(productlist.get(i).username)){
                orderNumber.add(productlist.get(i).orderid);
                rowData[0] = productlist.get(i).getOrderid();
                rowData[1] = productlist.get(i).getDate();
                rowData[2] = productlist.get(i).getTotal();
                rowData[3] = productlist.get(i).getAddress();
                rowData[4] = productlist.get(i).getTelephone();
                rowData[5] = productlist.get(i).getUsername();
                model.addRow(rowData);
                }
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    }
     
          public final void Table1(){          
        try {
            FileInputStream fin = new FileInputStream ("orderitem.txt");
            ObjectInputStream ois = new ObjectInputStream(fin);
            ArrayList<OrderItem> productlist1 = new ArrayList<>();
            productlist1 = (ArrayList<OrderItem>) ois.readObject();
            DefaultTableModel model = (DefaultTableModel)tblitem.getModel();
            Object rowData[] = new Object[3];
            for(int i = 0; i < productlist1.size(); i++){
                for(int j = 0; j < orderNumber.size(); j++){
                    if(orderNumber.get(j).equals(productlist1.get(i).getOrderNo())){
                        rowData[0] = productlist1.get(i).getOrderNo();
                        rowData[1] = productlist1.get(i).getItem();
                        rowData[2] = productlist1.get(i).getQuantity();
                         model.addRow(rowData);
                    }
                    
                }
               
              
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException | ClassNotFoundException ex) {
            
        } 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        btnorders = new javax.swing.JButton();
        btnmycart = new javax.swing.JButton();
        btncategory = new javax.swing.JButton();
        btnlodecomplain = new javax.swing.JButton();
        btninqiure = new javax.swing.JButton();
        btnaboutus = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        btnhome = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(java.awt.SystemColor.controlHighlight);
        btnback.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnback.setText("Back   ");
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 650, -1, -1));

        btnorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderbutton.JPG"))); // NOI18N
        btnorders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnorders.setContentAreaFilled(false);
        btnorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersActionPerformed(evt);
            }
        });
        getContentPane().add(btnorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, -1));

        btnmycart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cartbutton.JPG"))); // NOI18N
        btnmycart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnmycart.setContentAreaFilled(false);
        btnmycart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycartActionPerformed(evt);
            }
        });
        getContentPane().add(btnmycart, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 150, -1));

        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/catesmall.jpg"))); // NOI18N
        btncategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 10));

        btnlodecomplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locsmall.jpg"))); // NOI18N
        btnlodecomplain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnlodecomplain.setContentAreaFilled(false);
        btnlodecomplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodecomplainActionPerformed(evt);
            }
        });
        getContentPane().add(btnlodecomplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 10));

        btninqiure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inqui.jpg"))); // NOI18N
        btninqiure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btninqiure.setContentAreaFilled(false);
        btninqiure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninqiureActionPerformed(evt);
            }
        });
        getContentPane().add(btninqiure, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 70, 10));

        btnaboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutus.jpg"))); // NOI18N
        btnaboutus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnaboutus.setContentAreaFilled(false);
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });
        getContentPane().add(btnaboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 70, 10));

        btnsignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/singnout.jpg"))); // NOI18N
        btnsignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignout.setContentAreaFilled(false);
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 60, 10));

        lbl1.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        lbl1.setForeground(new java.awt.Color(102, 102, 102));
        lbl1.setText("MY ORDERED PRODUCTS");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 340, 30));

        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Date", "Total", "Address", "Telephone", "Customer"
            }
        ));
        jScrollPane1.setViewportView(tblorder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 540, 150));

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Product Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(tblitem);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 540, 150));

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home3.JPG"))); // NOI18N
        btnhome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.JPG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersActionPerformed
        Orders order = new Orders();
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnordersActionPerformed

    private void btnmycartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycartActionPerformed
        CustomerCart cart = new CustomerCart(username);
        cart.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnmycartActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        CategorySearch cate = new CategorySearch();
        cate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnlodecomplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodecomplainActionPerformed
        CustomerComplains com = new CustomerComplains();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlodecomplainActionPerformed

    private void btninqiureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninqiureActionPerformed
        CustomerInquire inquire = new CustomerInquire();
        inquire.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninqiureActionPerformed

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
        CustomerAboutUs aboutus = new CustomerAboutUs();
        aboutus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoutActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsignoutActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        CustomerPage cus = new CustomerPage();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btninqiure;
    private javax.swing.JButton btnlodecomplain;
    private javax.swing.JButton btnmycart;
    private javax.swing.JButton btnorders;
    private javax.swing.JButton btnsignout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTable tblitem;
    private javax.swing.JTable tblorder;
    // End of variables declaration//GEN-END:variables
}
